### ISSUE TITLE
I really like seeing my bot rebranded

### ISSUE THREAD

**Issue by rxnk** [NERVCorporation/rei#1]
Very epic, My bot has been renamed to Rei and made into a Github bot anyone can setup

**Comment by leeaahhh** [comment]
May I know what your bot exactly is? I got the bot source from a friend, made some improvement and put it on GitHub, this is the second time I've seen someone talk about it. Maybe we could talk about it on Discord as I'm really confused about what's going on.

**Comment by rxnk** [comment]
add me on discord @ethan29183
