### ISSUE TITLE
???

### ISSUE THREAD

**Issue by c-ic** [NERVCorporation/rei#4]
looks awfully familiar huh https://github.com/kzxyo/skidcity/tree/main/bleed/

**Comment by leeaahhh** [comment]
First of all, I did not obtain the original source code from there, and this repository doesn't have any license as of the time I'm writing this which allows anyone to just take this source code if they want and not credit the original creator and do whatever they want with it. Second of all, if you made an effort to atleast look a little bit into the code of the repository you provided, you'll see that almost everything is different there. For example, the react command in the LastFM category of the bot.

Here's the command from the bleed remake. 
![image](https://github.com/user-attachments/assets/3c062454-783b-43c8-b527-809f9e52b545)

Here is the command from my bot Rei.
![image](https://github.com/user-attachments/assets/a1fa1f6d-b993-4858-8c66-c9b2cdae2262)

You can see that those two are **completely different**. As of the origin of the original source code I am using, I've obtained it from a friend after he permanently shut down his bot and gave the source to me in private. I don't know if it's stolen or not, but I found it as a good base for a Discord bot and improved it with my own taste and open-sourced it for the world to enjoy the features I implemented!

**Comment by c-ic** [comment]
Weird how the file structure is near identical, on top of this, you've already been called out for completely copying another leaked bot.  I wouldn't exactly fully believe you just happened to make a structure that looks nearly the same on top of having  1:1 snippets of code.

**Comment by leeaahhh** [comment]
Near identical? They are totally different? If you want the original source, I can give it.

https://git.sr.ht/~igna/shiro
