### ISSUE TITLE
Update commands for hybrid compatibility

### ISSUE THREAD

**Issue by angelizado** [NERVCorporation/rei#6]
Some commands in the bot are not compatible with the hybrid command system introduced in `discord.py` (v2.x).  Refactor the current command setup to work with both prefix commands and slash commands, as hybrid commands allow for both.

**Goal is to fully integrate hybrid commands into the bot, to merge [slash](https://github.com/NERVCorporation/rei/tree/slash) branch into [main](https://github.com/NERVCorporation/rei/tree/main).**
> _commit: https://github.com/NERVCorporation/rei/commit/ec6deb705f37cc01aa7c014a88fdf065f63060ec_

**Comment by leeaahhh** [comment]
I'm almost done with this, just needs fixed on some commands and I'll merge your branch

**Comment by angelizado** [comment]
> I'm almost done with this, just needs fixed on some commands and I'll merge your branch

good girl

**Comment by Omarplayz233** [comment]
crazy 😭

**Comment by angelizado** [comment]
Closed as this got merged
